namespace: kevin197011
name: krun
version: 0.1.1
readme: README.md
authors:
  - kevin197011 <kevin197011@gmail.com>
description: Ansible module for krun remote script runner
license:
  - MIT
repository: https://github.com/kevin197011/ansible-collection-krun.git